### PR TITLE
KairosDb format specification as Protobuf.

### PR DESCRIPTION
**Pull request by vjkoskela**

### CODE REVIEW

**Comment by vjkoskela** [comment]
Extracted from https://github.com/ArpNetworking/kairosdb-histograms/pull/10 and required to evolve KDB to 64-bit as the existing format is not extensible.

**Comment by BrandonArp** [comment]
Why extract it? It's an internal storage format

**Comment by vjkoskela** [comment]
I agree it was not strictly necessary; however, we have done this with other "internal" formats like Prometheus (used by MAD only). My primary motivation for this is that the Protobuf code generated code conflicts with some of our code analysis tools (e.g. checkstyle, findbugs, javadoc).

1) These conflicts seem to change from version to version of the Protobuf code generator (e.g. https://github.com/InscopeMetrics/client-protocol/pull/18, https://github.com/ArpNetworking/metrics-aggregator-protocol/pull/15, https://github.com/ArpNetworking/prometheus-remote-protocol/pull/4).

2) Some of these tools have either cumbersome (e.g. Findbugs) or non-existent (e.g. Javadoc) controls for selectively disabling the associated checks. Consequently, we end up using a blunt approach of disabling it project wide. 

3) Packaging the format separately means that development environments don't need to deal with code generation (e.g. cmd line generation first, then magic directory marking, and only then things work in your IDE).

Anyway, that was my conclusion last night after building+testing the whole thing inline in kairosdb-extensions; and I figured if I didn't extract it now, then it would probably never happen.

**Comment by vjkoskela** [comment]
Completed porting (and expanding) the performance tests for KairosDb-Extensions to verify the change. I was surprised how much slower the new implementation was against the old one. 

After some digging online the general consensus was that `map` is actually somewhat bloated and slow. I altered the new format to use dual repeated fields (keys and counts). The results were impressive:

v1 size = 74444088
v1 timing = 1.2541, 1.2665

v2 size (with map) = 57735465
v2 timing (with map) = 1.734

v2 size (with repeat fields) = 33100769
v2 timing (with repeat fields) = 1.375

The pb-repeat format was only about 10% slower than v1 compared to pb-map which was 38% slower. However, what was unexpected was to see the additional space savings! The pb-repeat format cuts the representation down to 44% of v1 compared to only 77% for pb-map of v1.

This representation is definitely less user friendly; however, as a private storage format hidden by a more user friendly API I think these gains are worth it. Feedback encouraged.

**Review by philkjacobs — APPROVED** [review]

**Review by philkjacobs — APPROVED** [review]

**Review by philkjacobs — APPROVED** [review]

**Review by philkjacobs — CHANGES_REQUESTED** [review]
requesting changes so that I can re-stamp it in case that fixes this

**Review by philkjacobs — APPROVED** [review]

**Pull request merged**
